on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.ACCOUNT_SID }}
          auth_token: ${{ secrets.AUTH_TOKEN }}
          to_whatsapp_no: ${{ secrets.TO_WHATSAPP_NO }}


        uses: Glennpedley/CluelessDevOps/whatsapp-push-notify-action@master
      
      - name : Run
        run: |
          echo 'Start!'
