name: When one of the folloiwning events occur in the master branch, a message is sent to the Whatsapp.
on: [push, pull_request, issues, fork, watch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: whatsapp-notify

        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}
          
        uses: Glennpedley/whatsapp-push-notify-action@master

     
      
      - name : Run
        run: |
          echo 'Start!'
